root_dir: /n/holystore01/LABS/itc_lab/Users/sjeffreson
save_dir: /n/holystore01/LABS/itc_lab/Users/sjeffreson/GalactISM_output/ETG-medM
subdir: ETGs/medM-output
snap_prefix: snap-DESPOTIC

beg_snap: 100
end_snap: 400
snap_step: 10

xymax_kpc: 2.0
xybin_width_pc: 80.0
total_height_kpc: 0.3
rotcurve_rsln_pc: 20.0
